name: 1 🚀 Dev 


on:

  push:
    branches:
      - main
      - 'fix/**'
      - 'test/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/**'
      - 'parameters-production.json'
      - 'dynamo.py'  
      - 'rollback-dynamo.py'
      - 'tablas/**'
      - 'pre-commit-config.yaml'
      - '.flake8'
      - 'pyproject.toml'
      - 'isort.cfg'
      - '.cz.yaml'

  workflow_dispatch:
    inputs:
      dynamodb:
        description: 'Activa la insercion de datos de la carpeta tablas DynamoDB'
        required: false
        default: false
        type: boolean

concurrency: develop

jobs:

  ############ PUSH A RAMA MAIN ##############
  # Si se hace push a la rama main:
  DevDeploy:
    if: ${{ startsWith( github.ref, 'refs/heads/fix') || github.ref == 'refs/heads/main'  }}
    uses: victoraguilarc/aws-sam-github/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "develop"
      region: us-east-1
      ref: ${{ github.sha }}
      dynamodb: ${{ github.event.inputs.dynamodb }}
      region_dr: us-west-2
    secrets: inherit
permissions:
  id-token: write
  contents: read